version: "3.8"

services:
  api:
    image: opc-pro-scheduler
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: opc_pro
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
