"""Updated name field

Revision ID: 4b4604acc3ec
Revises: ebcef2ba8406
Create Date: 2023-12-20 18:31:05.640008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4604acc3ec'
down_revision: Union[str, None] = 'ebcef2ba8406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opc_servers_name', table_name='opc_servers')
    op.create_index(op.f('ix_opc_servers_name'), 'opc_servers', ['name'], unique=True)
    op.drop_index('ix_plc_servers_name', table_name='plc_servers')
    op.create_index(op.f('ix_plc_servers_name'), 'plc_servers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plc_servers_name'), table_name='plc_servers')
    op.create_index('ix_plc_servers_name', 'plc_servers', ['name'], unique=False)
    op.drop_index(op.f('ix_opc_servers_name'), table_name='opc_servers')
    op.create_index('ix_opc_servers_name', 'opc_servers', ['name'], unique=False)
    # ### end Alembic commands ###
