"""Removed job_type field

Revision ID: bf2cae1a2a25
Revises: ab08286a6bc8
Create Date: 2023-12-02 19:20:17.851745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2cae1a2a25'
down_revision: Union[str, None] = 'ab08286a6bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
