"""Increased node_id field length

Revision ID: e78188bde841
Revises: bf2cae1a2a25
Create Date: 2023-12-10 21:55:33.670151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78188bde841'
down_revision: Union[str, None] = 'bf2cae1a2a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=True)
    op.alter_column('opc_servers', 'node_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opc_servers', 'node_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    # ### end Alembic commands ###
